"""Initial

Revision ID: 6f553d0dcd9d
Revises: 8ecd5dda3cb2
Create Date: 2024-04-08 00:09:39.032435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f553d0dcd9d'
down_revision: Union[str, None] = '8ecd5dda3cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
