"""Initial

Revision ID: 8ecd5dda3cb2
Revises: a3cccf9a11db
Create Date: 2024-04-07 23:38:20.130476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ecd5dda3cb2'
down_revision: Union[str, None] = 'a3cccf9a11db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
